global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api-node"
    static_configs:
      - targets: ["api-node:3000"]

  - job_name: "core-go"
    static_configs:
      - targets: ["core-go:8080"]
      
  - job_name: "worker-python"
    static_configs:
      - targets: ["worker-python:9000"]
